name: Build

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - test

jobs:
  build:
    runs-on: self-hosted
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      DEPLOYMENT_ENV: ${{ vars[format('{0}_DEPLOYMENT_ENV', inputs.environment)] }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
        with:
          gradle-version: 7.5

      - uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        with:
          params: |
            ARTIFACTORY_URL=/artifactory/url
            ARTIFACTORY_USER=/artifactory/user
            ARTIFACTORY_PASSWORD=/artifactory/password

      - name: Build libraries
        run: |
          gradle -b build.gradle bootJar -Dset.root.project.build.filename=true

      - name: Assume role in target account
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets[format('{0}_ACCOUNT', inputs.environment)] }}:role/delegatedadmin/developer/ab2d-${{ inputs.environment }}-github-actions

      - name: Build and push docker image
        env:
          ACCOUNT: ${{ secrets[format('{0}_ACCOUNT', inputs.environment)] }}
          ENV: ${{ inputs.environment }}
        run: |
          ECR_DOMAIN="$ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com"

          aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_DOMAIN

          if [ "$ENV" == "test" ]; then
            ECR_REPO="ab2d-impl-services"
          else
            ECR_REPO="ab2d-$ENV-services"
          fi
          ECR_URI="$ECR_DOMAIN/$ECR_REPO"
          TAG="$ECR_URI:event-service"

          # If we're building for test or dev, build the image
          if [ "$ENV" = "test" ] || [ "$ENV" = "dev" ]; then
            docker build -t $TAG .
            docker push "$TAG"

            # Push to special tag for promotion if this is run on main
            if [ "$GITHUB_REF" == "refs/heads/main" ]; then
              SHA_SHORT=$(git rev-parse --short HEAD)
              echo "Tagging image for commit sha $SHA_SHORT"
              docker tag "$TAG" "$ECR_URI:event-service-main-$SHA_SHORT"
              docker push "$ECR_URI:event-service-main-$SHA_SHORT"
            fi
          fi

          # If the environment is prod or prod-test, re-tag from test
          if [ "$ENV" = "prod" ] || [ "$ENV" = "prod-test" ]; then
            TEST_ACCOUNT=${{ secrets.TEST_ACCOUNT }}
            TEST_ECR_DOMAIN="$TEST_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com"
            TEST_ECR_URI="$TEST_ECR_DOMAIN/ab2d-impl-services"

            echo "Logging in to test ECR to pull image"
            aws ecr get-login-password | docker login --username AWS --password-stdin $TEST_ECR_DOMAIN

            echo "Pulling test image"
            docker pull "$TEST_ECR_URI:event-service"

            echo "Re-tagging for $ENV"
            docker tag "$TEST_ECR_URI:event-service" "$ECR_URI:event-service"

            echo "Pushing re-tagged image to $ENV ECR"
            docker push "$ECR_URI:event-service"
          fi

