name: Deploy-Main

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  Test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2

      - name: Set env vars
        run: |
          shopt -s expand_aliases # https://github.com/actions/toolkit/issues/766#issuecomment-928305811
          alias param="aws ssm get-parameter --output text --query Parameter.Value --with-decryption --name"

          artifactory_url="$(param /artifactory/url)"
          echo "ARTIFACTORY_URL=$artifactory_url" >> "$GITHUB_ENV"

          artifactory_user="$(param /artifactory/user)"
          echo "ARTIFACTORY_USER=$artifactory_user" >> "$GITHUB_ENV"

          artifactory_password="$(param /artifactory/password)"
          echo "::add-mask::$artifactory_password"
          echo "ARTIFACTORY_PASSWORD=$artifactory_password" >> "$GITHUB_ENV"

      - name: Build Libraries
        run: gradle -b build.gradle bootJar -Dset.root.project.build.filename=true

      - name: Build Docker Image
        run: ./scripts/build-docker-image.sh   


