name: promote-events

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - prod_test
          - prod
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  promote:
    runs-on: self-hosted
    steps:
      - name: Determine environment for PR vs manual
        id: set-env
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "env_name=prod_test" >> $GITHUB_OUTPUT
          else
            echo "env_name=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          fi

      - uses: aws-actions/configure-aws-credentials@v4.0.2
        env:
          ACCOUNT: ${{ steps.set-env.outputs.env_name == 'prod_test' && 'test' || 'prod_test' }}
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets[format('{0}_ACCOUNT', env.ACCOUNT)] }}:role/delegatedadmin/developer/ab2d-${{ env.ACCOUNT }}-github-actions

      - name: Set source/destination ECR config
        run: |
          if [ "${{ steps.set-env.outputs.env_name }}" == "prod_test" ]; then
            echo "SOURCE_REPO=ab2d-impl-services" >> $GITHUB_ENV
            echo "DEST_REPO=ab2d-prod-test-services" >> $GITHUB_ENV
          elif [ "${{ steps.set-env.outputs.env_name }}" == "prod" ]; then
            echo "SOURCE_REPO=ab2d-prod-test-services" >> $GITHUB_ENV
            echo "DEST_REPO=ab2d-prod-services" >> $GITHUB_ENV
          fi
          echo "TAG_NAME=event-service" >> $GITHUB_ENV

      - name: Retag image in ECR
        env:
          ACCOUNT_ID: ${{ secrets[format('{0}_ACCOUNT', steps.set-env.outputs.env_name == 'prod_test' && 'test' || 'prod_test')] }}
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: |
          ECR_REPO_DOMAIN="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
          TOKEN="$(aws ecr get-authorization-token --output text --query 'authorizationData[].authorizationToken')"
          CONTENT_TYPE="application/vnd.docker.distribution.manifest.v2+json"

          echo "Fetching manifest for $TAG_NAME from $SOURCE_REPO"
          MANIFEST="$(curl -sS -H "Authorization: Basic $TOKEN" -H "Accept: $CONTENT_TYPE" \
            "https://$ECR_REPO_DOMAIN/v2/$SOURCE_REPO/manifests/$TAG_NAME")"

          echo "Tagging image as $TAG_NAME in $DEST_REPO"
          curl -sS -X PUT -H "Authorization: Basic $TOKEN" -H "Content-Type: $CONTENT_TYPE" \
            -d "$MANIFEST" "https://$ECR_REPO_DOMAIN/v2/$DEST_REPO/manifests/$TAG_NAME"
